config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :users, only: [:new, :index] do
    collection do
      get 'logout'
      get 'credit_regist'
    end
  end
  resources :items do
    member do
      get "buy"
      get "pay"
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
  end
  resources :categories, only: :index do
    collection do
      get 'parent_list'
      get 'child_list'
      get 'grandchild_list'
    end
  end
  resources :cards, only: [:new, :create, :show, :destroy] do
  end 
  resources :favorites, only: [:index, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :name, :email, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthday ,presence: true
  validates :first_name,:last_name,
            format: {
              with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/,
              message: "は全角で入力して下さい"
            }
  validates :first_name_kana,:last_name_kana,
            format: {
              with: /\A[ぁ-んー－]+\z/,
              message: "は全角ひらがなのみで入力して下さい"
            }

  has_many :cards
  has_many :items
  has_one :address
  has_many :sns_credentials

  # お気に入り登録用
  has_many :favorites
  has_many :fav_items, through: :favorites, source: :item
  
  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    # SNS認証したかどうかを判定するために、@snsという変数を新規登録画面に持っていくため
    { user: user, sns: sns }
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    # ＠userへ代入する際にハッシュから値を取り出す
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
    else
      # ＠sns_idという変数を作り、新規登録画面で扱えるようにする
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end


  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  def create
    # params[:sns_auth]が送られて来た時だけDevise.friendly_tokenを使ってパスワードを自動生成する
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
    redirect_to root_path
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attributes])
  end

  def address_params
    params.require(:address).permit(:postal_code, :prefecture_id, :city, :house_number, :house_name)
  end



  

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def index
  end

  def logout
  end

  # payjpをロード
  # require "payjp"
  def credit_regist
  #   card = Card.find_by(user_id: 1)
  #   Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
  #   customer = Payjp::Customer.retrieve(card.customer_id)
  #   @card = Payjp::Customer.retrieve(card.customer_id).cards.data[0]
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_header.html.haml
%header.xxel
  .caxl
    .seou
      .ewwr
        %a.fmwa
          = link_to image_tag("http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg"), class: "fmwa-img"
      %form.iklw
        %input.hubx{placeholder:"探し物は何ですか？"}
        %button.flds
          =fa_icon "search"
    .jpcs
      .jezi
        .iviz
          %a.juqf
            =fa_icon "bars"
            %svg.fknb
            カテゴリーから探す          
        .iviz
          %a.juqf
            =fa_icon "tag"
            %svg.rnbr
            ブランドから探す
      .ftie
        .davj
          %a.hleh
            新規会員登録
        .flxl
          %a.davx
            ログイン

app/views/users/_side-navbar.html.haml
.l-side
  %ul.nav-list
    %li
      = link_to "/users" do
        マイページ
    %li
      = link_to "" do
        お知らせ
    %li
      = link_to 'お気に入り一覧', favorites_path, method: :get
    %li
      = link_to "" do
        出品する
    %li
      = link_to "" do
        下書き一覧
    %li
      = link_to "" do
        出品した商品 - 出品中
    %li
      = link_to "" do
        出品した商品 - 取引中
    %li
      = link_to "" do
        出品した商品 - 売却済み
    %li
      = link_to "" do
        購入した商品 - 取引中
    %li
      = link_to "" do
        購入した商品 - 過去の取引
    %li
      = link_to "" do
        ニュース一覧
    %li
      = link_to "" do
        評価一覧
    %li
      = link_to "" do
        ガイド
    %li
      = link_to "" do
        お問い合わせ
  %h3.nav-head 設定
  %ul.nav-list
    %li
      = link_to "" do
        プロフィール
    %li
      = link_to "" do
        発送元・お届け先住所変更
    %li
      = link_to "/users/credit_regist" do
        支払い方法
    %li
      = link_to "" do
        メール/パスワード
    %li
      = link_to "" do
        本人情報
    %li
      = link_to "" do
        電話番号の確認
    %li
      = link_to "/users/logout" do
        ログアウト

app/views/users/credit-regist.html.haml
.mypagemain
  = render 'users/side-navbar'
  .creditregist
    %h2.creditregist-head
      支払い方法
    .creditregist-inner
      .credit-list
        クレジットカード一覧
        %ul
          %li
      .creditadd
        .creditadd-btn
          = link_to "" do
            クレジットカードを追加する

app/views/users/credit_regist.html.haml
.mypagemain
  = render 'users/side-navbar'
  .creditregist
    %h2.creditregist-head
      支払い方法
    .creditregist-inner
      -# .credit-list
      -#   クレジットカード一覧
      -#   = "**** **** **** " + @card.last4
      -#   - exp_month = @card.exp_month.to_s
      -#   - exp_year = @card.exp_year.to_s.slice(2,3)
      -#   = exp_month + " / " + exp_year
      -#   = link_to card_path(@card), method: :delete, class: "destroy_btn" do
      -#     削除する
      .creditadd
        .creditadd-btn
          = link_to "クレジットカードを追加する", new_card_path
        ※追加済みの場合照会画面

app/views/users/index.html.haml
= link_to new_item_path, data: {"turbolinks" => false} do
  .salebtn
    .salebtn-name
      出品
    .salebtn-icon
      = icon('fa', 'camera fa-4x')

.pagehierarchy
  %ul
    %li
      %a(href="#") FURIMA > 
    %li マイページ

.mypagemain
  = render 'users/side-navbar'
  .usercontent
    .usericon
      .usericon-image
        = image_tag 'mypage/human-001.jpg', alt: ''
        -# アイコン
      .usericon-name
        = current_user.name

app/views/users/logout.html.haml
.logoutpagemain
  = render 'users/side-navbar'
  .logoutcont
    .logoutcont-btn
      = link_to "ログアウト", destroy_user_session_path, method: :delete

app/views/users/new.html.haml
%body
  .container
    .header
      %h1
        = link_to image_tag("http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg"), '#'
    .main
      .signup
        %h2.registration-head
          新規会員登録
        .registration-inner
          .registration-inner_cont
            = link_to new_user_registration_path, class: "registration-btn btn-mail" do
              = icon('fa', 'envelope', class: "btn-icon")
              メールアドレスで登録する
            = link_to "#", class: "registration-btn btn-facebook" do
              = icon('fa', 'facebook-square', class: "btn-icon")
              Facebookで登録する
            / = link_to user_facebook_omniauth_authorize_path, method: :post, class: "registration-btn btn-facebook" do
            /   = icon('fa', 'facebook-square', class: "btn-icon")
            /   Facebookで登録する
            = link_to "#", class: "registration-btn btn-google" do
              = icon('fa', 'google', class: "btn-icon")
              Googleで登録する
            / = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: "registration-btn btn-google" do
            / = icon('fa', 'google', class: "btn-icon")
            / Googleで登録する
    .footer
      %nav
        %ul
          %li
            =link_to "プライバシーポリシー", '#'
          %li
            =link_to "利用規約", '#'
          %li
            =link_to "特定商取引に関する表記", '#'
        = link_to image_tag("http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg"), '#'
      %p
        %small
          © FURIMA, Inc.