config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :users, only: [:new, :index] do
    collection do
      get 'logout'
      get 'credit_regist'
    end
  end
  resources :items do
    member do
      get "buy"
      get "pay"
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
  end
  resources :categories, only: :index do
    collection do
      get 'parent_list'
      get 'child_list'
      get 'grandchild_list'
    end
  end
  resources :cards, only: [:new, :create, :show, :destroy] do
  end 
  resources :favorites, only: [:index, :create, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :address
  has_many :images, dependent: :destroy
  belongs_to :category
  belongs_to :condition
  belongs_to :delivery_fee
  belongs_to :delivery_day
  belongs_to :status
  belongs_to :user
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  # お気に入り登録用
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: :user

  # 子モデルのバリデーションチェック
  validates_associated :images
  validates :images, presence: true

  # バリデーション
  validates :name,:explanation,:category_id,:condition_id,:delivery_fee_id,:prefecture_id,:delivery_day_id,:price, presence: true
  # ↓条件付き必須・・・カテゴリによって必須になる
  # validates :size, presence: true

  accepts_nested_attributes_for :images, allow_destroy: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :index_category_set, only: :index
  before_action :set_item, only: [:edit, :update, :destroy, :show, :buy, :pay]
  before_action :login_siyou, only: [:new, :buy, :edit]
  before_action :url_buy_dame, only: [:buy]
  before_action :url_edit_dame, only: [:edit]

  # payjpをロード
  require "payjp"

  def index
    @images = Image.all
    @categories = Category.where('ancestry IS NULL')
    @items = Item.where(status: 1).order('created_at ASC')
  end

  def show
    if user_signed_in?
      @favorite_find = @item.favorites.find_by(user_id: current_user.id)
    end
  end

  def new
    # 登録ボタン名
    @submit_btn = ['new','出品する']
    @item = Item.new
    @item.images.new
    # @item.users << current_user
    @category_parents = Category.where('ancestry IS NULL').map{ |category|[category.name, category.id] }
  end

  def create
    @category_parents = Category.where('ancestry IS NULL').map{ |category|[category.name, category.id] }

    @submit_btn = ['new','出品する']
    # バリデーションチェックで引っかかって出品画面に戻ったとき、上の変数がないとエラーになる。
    @status = 1
    # ステータスの状態を「出品中：１」にして登録する
    @item = Item.new(item_params)
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
      # 「render :new」ではなく「redirect_to」でnew画面を呼び出したいがエラーメッセージが表示されなくなってしまう
      # redirect_toにしてエラーメッセージをセッションで表示する方法に修正したい。
    end
  end

  def edit
    # 登録ボタン名
    @submit_btn = ['edit','更新する']
    @category_parents = Category.where('ancestry IS NULL').map{ |category|[category.name, category.id] }
    @category_childs = @item.category.parent.parent.children.map{ |category|[category.name, category.id] }
    @category_grandchilds = @item.category.parent.children.map{ |category|[category.name, category.id] }
    # binding.pry
  end

  def update
    @submit_btn = ['edit','更新する']
    @category_parents = Category.where('ancestry IS NULL').map{ |category|[category.name, category.id] }
    @category_childs = @item.category.parent.parent.children.map{ |category|[category.name, category.id] }
    @category_grandchilds = @item.category.parent.children.map{ |category|[category.name, category.id] }
    # ステータスの状態を「出品中：１」にして登録する
    @status = 1
    if @item.update(item_params)
      redirect_to item_path(@item), notice: '出品情報を更新しました'
    else
      render :edit
    end
  end
  
  def buy
    if @item.status_id != 2
      card = Card.where(user_id: current_user.id)
      # card = Card.where(user_id: 1)
      if card.exists?
        @card = Card.find_by(user_id: current_user.id)
        # @card = Card.find_by(user_id: 1)
        Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @card = Payjp::Customer.retrieve(@card.customer_id).cards.data[0]
      end
    else
      redirect_to item_path(@item)
    end
  end

  def pay
    if @item.status_id != 2
      @card = Card.find_by(user_id: current_user.id)
      @item.status_id = 2
      @item.save
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      # カードトークンを用いて支払いを作成する
      @charge = Payjp::Charge.create(
      amount: @item.price,
      customer: @card.customer_id,
      currency: 'jpy'
      )
      @card = Payjp::Customer.retrieve(@card.customer_id).cards.data[0]
    else
      redirect_to item_path(@item)
    end
  end

  # 親カテゴリーが選択された際に動く(Ajax)
  def get_category_children
    @category_children = Category.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された際に動く(Ajax)
  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def item_params
    params
    .require(
      :item
    )
    .permit(
      :name, 
      :explanation, 
      :category_id, 
      :size, 
      :brand_name, 
      :condition_id, 
      :status_id, 
      :delivery_fee_id, 
      :prefecture_id, 
      :delivery_day_id, 
      :price, 
      images_attributes: [:image, :_destroy, :id]
    )
    .merge(
      user_id: current_user.id,
      status_id: @status
    ) 
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def index_category_set
    search_anc = Category.where('ancestry IS NULL')
    array = []
    search_anc.each do |i|
      array << i[:id]
    end
    for num in array do
      search_anc = Category.where('ancestry LIKE(?)', "#{num}%")
      ids = []
      search_anc.each do |i|
        ids << i[:id]
      end
      items = Item.where(category_id: ids).order("id DESC").limit(10)
      instance_variable_set("@cat_no#{num}", items)
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def login_siyou
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def url_buy_dame
    if current_user == @item.user
      redirect_to items_path
    end
  end

  def url_edit_dame
    if current_user != @item.user
      redirect_to items_path
    end
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_category.html.haml
--# - @categories.each do |category|
%li.ctnmenu-item
  = link_to '#' do
    = category.name

app/views/items/_favorite_form.html.haml
- if @favorite_find.present?
  %li.opbtn.libtn.like_off
    %i.fa.fa-star
      = link_to 'お気に入りから削除', favorite_path(id: @item.id), method: :delete, remote: true, class: "like_off_btn" unless @item.user_id == current_user.id
- else
  %li.opbtn.libtn.like_on
    %i.fa.fa-star
      = link_to 'お気に入りに追加', favorites_path(item_id: @item.id), method: :post, remote: true, class: "like_on_btn" unless user_signed_in? && @item.user_id == current_user.id

app/views/items/_form.html.haml
.selmain
  = form_with model: @item, class: :form, local: true do |form|
    = render 'layouts/error_messages', model: form.object  
    %form.selmain-form
      .selmain-form_box
        .selimage
          .selimage-title
            %label 出品画像
            %span.required 必須
          %p 最大10枚までアップロードできます
          .selimage-function
            .selimage-function_input
              %label.clkarea#image-box
                .hidden-content#previews
                  = form.fields_for :images do |i|
                    .prepic{"data-index" => "#{i.index}"}
                      - if @item.persisted?
                        = image_tag @item.images[i.index].image.url, data: { index: i.index },class: 'tmpimg'
                        -#編集画面のプレビューの下の添付ボタン 
                        %label
                          = i.file_field :image ,:class => 'js-file hidden-field'
                        %label
                          = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
                          .js-remove 削除
                      - else
                        -# 新規画面で最初に表示されている添付ボタン
                        %label.tmpphoto{"new"=>"new"}
                          = icon('fa', 'camera', class: 'clkarea-icon')
                          = i.file_field :image ,:class => 'js-file'
                        -# %p sss
                  -# 編集画面で新規画像を追加できるように添付ボタンを追加
                  - if @item.persisted?
                    .js-file_group{"data-index" => "#{@item.images.count}","edit" => "new"}
                      %label.tmpphoto
                        = icon('fa', 'camera', class: 'clkarea-icon')
                        = file_field_tag :src, name: "item[images_attributes][#{@item.images.count}][image]", class: 'js-file'

                  -# いったんコメントアウト。余裕があれば下記のデザインにイメージ添付機能を当てはめたい
                  -# = form.fields_for :images do |i|
                  -#   %input.clkarea-input.js-file{:type => 'file'}
                  -#   = icon('fa', 'camera', class: 'clkarea-icon')
                  -#   %p.clkarea-text クリックしてファイルをアップロード
      %hr
      .selmain-form_box
        .selname
          .selname-title
            %label 商品名
            %span.required 必須
          .selname-function
            .selname-function_input
              = form.text_field :name, :placeholder => '40文字まで', :class => 'selname-text'
        .selspace
        .selname
          .selname-title
            %label 商品の説明
            %span.required 必須
          .selname-function
            .selname-function_input
              = form.text_area :explanation, :placeholder => '1,000文字以内', :class => 'selexplanation-text js-text'
              %p.js-text-count 0/1000
      %hr
      .selmain-form_box
        .seldetail.categ
          %p.seldetail-main 商品の詳細
          .seldetail-title
            %label カテゴリー
            %span.required 必須
          - if @submit_btn[0] == 'new'
            .seldetail-function
              .seldetail-function_input
                = form.select :parent_id, @category_parents, { include_blank: "選択して下さい"}, { class: "selcategory-select", id: 'parent_category' }
          - if @submit_btn[0] == 'edit'
            .seldetail-function
              .seldetail-function_input
                = form.select :parent_id, @category_parents, { include_blank: "選択して下さい", selected: @item.category.parent.parent.id }, { class: "selcategory-select", id: 'parent_category' }
            .seldetail-function#children_wrapper
              .seldetail-function_input
                = form.select :child_id, @category_childs, { include_blank: "選択して下さい", selected: @item.category.parent.id }, { class: "selcategory-select", id: 'child_category' }
            .seldetail-function#grandchildren_wrapper
              .seldetail-function_input
                = form.select :category_id, @category_grandchilds, { include_blank: "選択して下さい", selected: @item.category_id }, { class: "selcategory-select", id: 'grandchild_category' }
        -# ↓カテゴリによって表示する内容、ひとまず条件なしで表示
        .selspace
          .seldetail-title
            %label サイズ
            %span.required 必須
          .seldetail-function
            .seldetail-function_input
              = form.text_field :size, :placeholder => 'サイズ', :class => 'selname-text'
        .selspace
          .seldetail
          .seldetail-title
            %label ブランド
            %span.discretion 任意
          .seldetail-function
            .seldetail-function_input
              = form.text_field :brand_name, :placeholder => '例）シャネル', :class => 'selbrand-text'
        .selspace
        .seldetail
          .seldetail-title
            %label 商品の状態
            %span.required 必須
          .seldetail-function
            .seldetail-function_input
              = form.select :condition_id, Condition.all.map { |status|[status.name, status.id] }, { include_blank: "選択して下さい", selected: @item.condition_id }, { class: "selstatus-select" }
      %hr
      .selmain-form_box
        .seldelovery
          %p.seldelovery-main 配送について？
          .seldelovery-title
            %label 配送料の負担
            %span.required 必須
          .seldelovery-function
            .seldelovery-function_input
              = form.select :delivery_fee_id, DeliveryFee.all.map { |status|[status.name, status.id] }, { include_blank: "選択して下さい", selected: @item.delivery_fee_id }, { class: "seldelfee-select" }
        .selspace
        .seldelovery
          .seldelovery-title
            %label 発送元の地域
            %span.required 必須
          .seldelovery-function
            .seldelovery-function_input
              = form.select :prefecture_id, Prefecture.all.map { |status|[status.name, status.id] }, { include_blank: "選択して下さい", selected: @item.prefecture_id }, { class: "selshiori-select" }
        .selspace
        .seldelovery
          .seldelovery-title
            %label 発送までの日数
            %span.required 必須
          .seldelovery-function
            .seldelovery-function_input
              = form.select :delivery_day_id, DeliveryDay.all.map { |status|[status.name, status.id] }, { include_blank: "選択して下さい", selected: @item.delivery_day_id }, { class: "selshiori-select" }
      %hr
      .selmain-form_box
        .selprice
          %p.selprice-main 価格（¥300〜9,999,999）
          .selprice-title
            %label 販売価格
            %span.required 必須
          .selprice-function
            .selprice-function_input
              = form.text_field :price, :placeholder => '0', :class => 'selprice-text'
          -# %p.selprice-error 300以上9999999以下で入力してください
      %hr
      .selmain-form_box
        .selsubmit
          .selsubmit-button
            = form.submit @submit_btn[1], :class => 'selsubmit-button_sell'
            -# %input.selsubmit-button_sell{type: "submit", value: "出品する"} 
            -# = form.submit '下書きに保存', :class => 'selsubmit-button_save'
            -# %input.selsubmit-button_save{type: "submit", value: "下書きに保存"} 
            - if @submit_btn[0] == 'edit'
              = link_to '商品を削除する', item_path, method: :delete , :class => 'selsubmit-button_delete'
            -# 前回画面にもどる
            = link_to :back, class: "selsubmit-button_back" do
              もどる

app/views/items/_item.html.haml
%li.ctnlist-item
  -# - @cat_no1.each do |item|
  -# -@items.each do |item| 
  = link_to item_path(id: item.id) ,class: "ctnlist-item_link" do
    - ft_image = item.images.first
    = image_tag ft_image.image.url, class: "ctnlist-item_img"
    .ctnlist-item_name
      %h3.ctn-item_name
        = item.name
      .ctn-item_detail
        %ul.ctn-price_box
          %li.ctn-item_price
            = item.price
            円
          %li.ctn-item_price
            = icon('fa', 'star', class: 'clkarea-icon')
            0

app/views/items/buy.html.haml
.body
  .purchase-main
    .purchase-box
      %h2.purchase-ttl
        購入内容の確認
      .item-cont
        .image
          = image_tag @item.images.first.image.url
        .details
          .item-name
            %p.price
              = @item.name

      .price-cont
        .price-left
          支払い金額
        .price-right
          = @item.price
          円

      .payment-cont
        %h3.payment-left
          .payment-method
            支払い方法：クレジットカード
            .card-info
            - if Card.where(user: current_user).exists?
              .card-num
                = "**** **** **** " + "#{@card.last4}"
              .expiration-date
                有効期限
                = @card.exp_month
                = @card.exp_year
            - else     
              = link_to new_card_path, class: "" do
                クレジットカード登録
        .payment-right
          -# = link_to "変更する", "#", calss:"update-btn"
          
            
      .deliveryDestination-cont
        %h3.deliveryDestination-left
          配送先
          .postalcode
            = "〒#{Address.find_by(user: current_user).postal_code.to_s.insert(3, "-")}"
          .address
            = Address.find_by(user: current_user).prefecture.name
            = Address.find_by(user: current_user).city
            = Address.find_by(user: current_user).house_name
              - unless Address.find_by(user: current_user).house_number == nil
              = Address.find_by(user: current_user).house_number
          .username
            = current_user.first_name
            = current_user.last_name
        .deliveryDestination-right
          -# = link_to "変更する", "#", calss:"update-btn"

      .purchase-btn
        - if Card.where(user: current_user).exists?
          .submit-btn        
            = link_to pay_item_path(@item), class: "" do
              購入を確定する
        - else
          .submit-btn        
            = link_to new_card_path, class: "" do
              クレジットカード登録
        

app/views/items/edit.html.haml
= render partial: 'form', locals: { item: @item }

app/views/items/index.html.haml
- if user_signed_in?
  = link_to new_item_path, data: {"turbolinks" => false} do
    .salebtn
      .salebtn-name
        出品
      .salebtn-icon
        = icon('fa', 'camera fa-4x')

.mainvisual
  .mcontent
    .mcontent-title
      人生を変えるフリマアプリ
    .mcontent-text
      FURIMAはだれでもかんたんに出品・購入できる
      %br
      フリマアプリです
    .mcontent-btn
      = link_to '#' do
        = image_tag 'appDL.svg', class: 'appdl'
      = link_to '#' do
        = image_tag 'gglDL.svg', class: 'appdl'

.subtitle
  FURIMAが選ばれる3つの理由

%ul.usagelists
  %li.list
    .list-pic
      .number
        %span
          １
      = image_tag 'pict-reason-01.jpg'
    %h3.list-text
      3分ですぐに出品
    .list-description
      スマホで入力するだけで簡単に出品できる！
  %li.list
    .list-pic
      .number
        %span
          ２
      = image_tag 'pict-reason-02.jpg'
    %h3.list-text
      3分ですぐに出品
    .list-description
      スマホで入力するだけで簡単に出品できる！
  %li.list
    .list-pic
      .number
        %span
          ３
      = image_tag 'pict-reason-03.jpg'
    %h3.list-text
      3分ですぐに出品
    .list-description
      スマホで入力するだけで簡単に出品できる！

.topmiddledl
  .mcontent
    .mcontent-title
      会員数日本一位
    .mcontent-text
      FURIMAは、フリマアプリで最も人気。
      %br
      出品・購入回数も業界最多です！
      %br
      ほしかったあの商品に出会えるかもしれません。
    .mcontent-btn
      = link_to '#' do
        = image_tag 'appDL.svg', class: 'appdl'
      = link_to '#' do
        = image_tag 'gglDL.svg', class: 'appdl'


.subtitle
  FURIMAの特徴

%ul.topfeature
  %li.list
    .list-pic
      = image_tag 'icon-01.png'
    %h3.list-text
      簡単に売り買いできる
    .list-description
      スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
  %li.list
    .list-pic
      = image_tag 'icon-03.png'
    %h3.list-text
      売上金は即日振込みに対応
    .list-description
      午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
  %li.list
    .list-pic
      = image_tag 'icon-04.png'
    %h3.list-text
      様々な支払いに対応
    .list-description
      お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

-# contents header の略
.ctnheader
  %h2.ctnheader-ttl
    出品一覧
  -# .ctnheader-menu
  -#   %ul
  -#     %li.ctnmenu-item
  -#       =link_to '#' do
  -#         レディース
  -#     %li.ctnmenu-item
  -#       =link_to '#' do
  -#         メンズ
  -#     %li.ctnmenu-item
  -#       =link_to '#' do
  -#         家電・スマホ・カメラ
  -#     %li.ctnmenu-item
  -#       =link_to '#' do
  -#         おもちゃ・ホビー・グッズ
-# contents area　の略
.ctnarea
  .ctnarea-hdr
    -# %h3.ctnarea-hdr_ttl
    -#   レディース新着アイテム
    .seemore
      =link_to '#' do
        もっと見る
  .ctnarea-list
    %ul
      = render template: "item", partial: "item", collection: @items
      -# %li.ctnlist-item
      -#   =link_to '#' do
      -#     %img.ctnlist-item_img{alt: "商品イメージ", src: "https://images.unsplash.com/photo-1586339392738-65847e399f7e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80"}
      -#     .ctnlist-item_name
      -#       商品タイトル
-# .ctnheader
-#   %h2.ctnheader-ttl
-#     人気のブランド
-#   .ctnheader-menu
-#     %ul
-#       = render template: "category", partial: "category", collection: @categories
      -# %li.ctnmenu-item
      -#   =link_to '#' do
      -#     シャネル
-# .ctnarea
-#   .ctnarea-hdr
-#     %h3.ctnarea-hdr_ttl
-#       ブランド新着アイテム
-#     .seemore
-#       =link_to '#' do
-#         もっと見る
-#   .ctnarea-list
-#     %ul
-#       %li.ctnlist-item
-#         =link_to '#' do
-#           %img.ctnlist-item_img{alt: "商品イメージ", src: "https://images.unsplash.com/photo-1586527484765-979a20639316?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80"}
-#           .ctnlist-item_name
-#             商品タイトル
-#       %li.ctnlist-item
-#         =link_to '#' do
-#           %img.ctnlist-item_img{alt: "商品イメージ", src: "https://images.unsplash.com/photo-1586527484765-979a20639316?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80"}
-#           .ctnlist-item_name
-#             商品タイトル
-#       %li.ctnlist-item
-#         =link_to '#' do
-#           %img.ctnlist-item_img{alt: "商品イメージ", src: "https://images.unsplash.com/photo-1586527484765-979a20639316?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80"}
-#           .ctnlist-item_name
-#             商品タイトル
-#       %li.ctnlist-item
-#         =link_to '#' do
-#           %img.ctnlist-item_img{alt: "商品イメージ", src: "https://images.unsplash.com/photo-1586527484765-979a20639316?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80"}
-#           .ctnlist-item_name
-#             商品タイトル
-#       %li.ctnlist-item
-#         =link_to '#' do
-#           %img.ctnlist-item_img{alt: "商品イメージ", src: "https://images.unsplash.com/photo-1586527484765-979a20639316?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80"}
-#           .ctnlist-item_name
-#             商品タイトル

app/views/items/new.html.haml
= render partial: 'form', locals: { item: @item }

app/views/items/pay.html.haml
.body
  .purchase-main
    .purchase-box
      .after-purchase-hdr
        %span.after-purchase-msg 発送をお待ちください
      %h2.after-purchase-ttl
        購入が完了しました
      .item-cont
        .image
          = image_tag @item.images.first.image.url
        .details
          .item-name
            %p.price
              = @item.name

      %form.price-cont
        .price-left
          支払い金額
        .price-right
          = @item.price
          円

      .payment-cont
        .payment-left
          .payment-method
            支払い方法：クレジットカード
            .card-info
            - if Card.where(user: current_user).exists?
              .card-num
                = "**** **** **** " + "#{@card.last4}"
              .expiration-date
                有効期限
                = @card.exp_month
                = @card.exp_year

      .deliveryDestination-cont
        %h3.deliveryDestination-left
          配送先
          .postalcode
            = "〒#{Address.find_by(user: current_user).postal_code.to_s.insert(3, "-")}"
          .address
            = Address.find_by(user: current_user).prefecture.name
            = Address.find_by(user: current_user).city
            = Address.find_by(user: current_user).house_name
              - unless Address.find_by(user: current_user).house_number == nil
              = Address.find_by(user: current_user).house_number
          .username
            = current_user.first_name
            = current_user.last_name
        
      .purchase-btn_top
        = link_to "トップページへ戻る", root_path, class:"afterpurchase-btn"

app/views/items/show.html.haml
.main
  .content
    .left
    .right
      .top
        .item
          %h2.item-name
            = @item.name
          .item-body
            %ul
              %li
                = image_tag @item.images.first.image.url, class: "o3mainimg"
                %ul.o3imglists
                  - @item.images.each do |img|
                    %li.o3img10
                      = image_tag img.image.url, class: "o3imglist"
          .item-price
            %span.o3detail
              = @item.price
              %span.o3en
                円
            .item-price_detail
              %span.o3zei
                (税込)
              %span.o3komi
                送料込み
          .idetail
            = @item.explanation
          .table
            %table
              %tbody
                %tr
                  %th
                    出品者
                  %td
                    = @item.user.name
                %tr
                  %th
                    カテゴリー
                  %td
                    = @item.category.parent.parent.name
                    %br
                    = @item.category.parent.name
                    %br
                    = @item.category.name
                %tr
                  %th
                    ブランド
                  %td
                    = @item.brand_name
                %tr
                  %th
                    商品のサイズ
                  %td
                    = @item.size
                %tr
                  %th
                    商品の状態
                  %td
                    = @item.condition.name
                %tr
                  %th
                    配送料の負担
                  %td
                    = @item.delivery_fee.name
                %tr
                  %th
                    配送元の地域
                  %td
                    = @item.prefecture.name
                %tr
                  %th
                    発送日の目安
                  %td
                    = @item.delivery_day.name
          - if current_user == @item.user
            = link_to edit_item_path, class: "o3btninedit", data: {"turbolinks" => false} do
              商品の情報を編集する
          - else
            = link_to buy_item_path(@item), class: "o3btninbuy" do
              この商品を購入する
          .option
            - if user_signed_in?
              %ul#favorite_btn
                = render 'favorite_form', item: @item, favorite: @favorite
                -# %li.opbtn.libtn
                -#   %i.fa.fa-star
                -#     お気に入り 9973               
            %ul.optional
              %li.opbtn
                = link_to '#' do
                  =fa_icon "flag"
                  不適切な商品の通報
        .comment
          %ul.ccontents
          %form.ncomment
            %textarea
            %p.notice
              相手のことを考え丁寧なコメントを心がけましょう。
              %br
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br
            %button.cobtn
              %i.fa.fa-comment
                コメントする
      %ul.links
        %li.leftli
          = link_to '#' do
            =fa_icon "angle-left"
            前の商品
        %li.rightli
          = link_to '#' do
            後ろの商品
            =fa_icon "angle-right"
      .related
        %a
          = link_to "メンズをもっと見る", '#'
        .productli