config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :users, only: [:new, :index] do
    collection do
      get 'logout'
      get 'credit_regist'
    end
  end
  resources :items do
    member do
      get "buy"
      get "pay"
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
  end
  resources :categories, only: :index do
    collection do
      get 'parent_list'
      get 'child_list'
      get 'grandchild_list'
    end
  end
  resources :cards, only: [:new, :create, :show, :destroy] do
  end 
  resources :favorites, only: [:index, :create, :destroy]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :item
  validates :postal_code, :prefecture_id, :city, :house_number ,presence: true

  validates :postal_code,presence: true,
            format: { 
              with: /\A\d{7}\z/, 
              message: "ハイフンなしの英数字で入力してください"
            }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :customer_id, :card_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :items
end

app/models/delivery_day.rb
class DeliveryDay < ApplicationRecord
  has_many :items
end

app/models/delivery_fee.rb
class DeliveryFee < ApplicationRecord
  has_many :items
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :item

  validates :image, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one :address
  has_many :images, dependent: :destroy
  belongs_to :category
  belongs_to :condition
  belongs_to :delivery_fee
  belongs_to :delivery_day
  belongs_to :status
  belongs_to :user
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  # お気に入り登録用
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: :user

  # 子モデルのバリデーションチェック
  validates_associated :images
  validates :images, presence: true

  # バリデーション
  validates :name,:explanation,:category_id,:condition_id,:delivery_fee_id,:prefecture_id,:delivery_day_id,:price, presence: true
  # ↓条件付き必須・・・カテゴリによって必須になる
  # validates :size, presence: true

  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :name, :email, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthday ,presence: true
  validates :first_name,:last_name,
            format: {
              with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/,
              message: "は全角で入力して下さい"
            }
  validates :first_name_kana,:last_name_kana,
            format: {
              with: /\A[ぁ-んー－]+\z/,
              message: "は全角ひらがなのみで入力して下さい"
            }

  has_many :cards
  has_many :items
  has_one :address
  has_many :sns_credentials

  # お気に入り登録用
  has_many :favorites
  has_many :fav_items, through: :favorites, source: :item
  
  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    # SNS認証したかどうかを判定するために、@snsという変数を新規登録画面に持っていくため
    { user: user, sns: sns }
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.haml
-if model.errors.any? 
  .alert
    %ul
      -model.errors.full_messages.each do |message| 
        %li= message

app/views/layouts/_footer.html.haml
.o3appban
  .o3inn
    %h2.o3inti
      だれでもかんたん、人生を変えるフリマアプリ
    %p.o3intex
      今すぐ無料ダウンロード！
    .o3inic
      = link_to image_tag("http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class:"o3abtn"), "#"
      = link_to image_tag("http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class:"o3abtn"), "#"

.o3footer
  %ul.o3conts
    %li.o3cont
      %h2.o3conhead
        FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社）", '#', class: "o3koumoku"
        %li
          = link_to "プライバシーポリシー", '#', class: "o3koumoku"              
        %li
          = link_to "FURIMA利用規約", '#', class: "o3koumoku"
        %li
          = link_to "ポイントに関する特約", '#', class: "o3koumoku"
    %li.o3cont
      %h2.o3conhead
        FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧", '#', class: "o3koumoku"
        %li
          = link_to "ブランド一覧", '#', class: "o3koumoku"
    %li.o3cont
      %h2.o3conhead
        ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド", '#', class: "o3koumoku"
        %li
          = link_to "FURIMAロゴ利用ガイドライン", '#', class: "o3koumoku"
        %li
          = link_to "お知らせ", '#', class: "o3koumoku"
  .o3logo
    %a
      = link_to image_tag("http://furima.tokyo/assets/logo-white-f61961ed5170064c5f33dd4524bdceeb5a5df2c83eb76fba31143f63fbab2c5e.svg", class:"o3footimg"), '#'
  %p.o3footfoot
    © FURIMA

app/views/layouts/_header.html.haml
%header.xxel
  .caxl
    .seou
      .ewwr
        %a.fmwa
          = link_to root_path do
            = image_tag "http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg", class: "fmwa-img"
      %form.iklw
        %input.hubx{placeholder:"探し物は何ですか？"}
        %button.flds
          =fa_icon "search"
    .jpcs
      .jezi
        .iviz
          = link_to categories_path, class: 'juqf' do
            =fa_icon "bars"
            %svg.fknb
            カテゴリーから探す          
        .iviz
          %a.juqf
            =fa_icon "tag"
            %svg.rnbr
            ブランドから探す
      .ftie
        - if user_signed_in?
          = link_to 'マイページ', users_path, class: 'hleh'
          = link_to 'ログアウト', logout_users_path, class: 'davx'
        - else
          = link_to '新規会員登録', new_user_path, class: 'hleh'
          = link_to 'ログイン', new_user_session_path, class: 'davx'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FreemarketSample73f
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if (request.path != new_user_path) &&(request.path != new_user_registration_path) && (request.path != addresses_path)
      = render "layouts/header"
    = yield
    - if (request.path != new_user_path) &&(request.path != new_user_registration_path) && (request.path != addresses_path)
      = render "layouts/footer"